### PR TITLE
skill, statue cheats; hair color preview/editing

### PR DESCRIPTION
**Pull request by rilne**
Added buttons on character page to add:
all base game skills
all base game skills, plus DLC skills
all base game skills, plus DLC skills, plus enemy skills

Also added/changed the global cheats with buttons for same.

Added button to global cheat page to set all characters battles/victories to a minimum of 100 (if either is already higher, it'll stay the same).
This immediately gets you the lvl 3 statues.
(for reference:: lvl 1: 20 victories, lvl 2: 50, lvl 3: 100)

Added a box showing the characters hair color, plus a hex readout of same.
Changing the hex box will change the color (if valid).
No picker yet.

Possible issues: I'm not completely sure of my bitset for base+dlc skills.
It should be correct, but let me know if anything slipped through.

### CODE REVIEW

**Comment by Soaprman** [comment]
Gonna be merging this manually since I was working on some stuff concurrently.

**Comment by rilne** [comment]
you might push the changes you have, and see if it can merge auto against those.

**Comment by Soaprman** [comment]
Actually, yeah, I might just give it a spin. I think it'll leave the codebase in a state that doesn't compile (I've changed the type of Character.LearnedSkills), but it should be something that auto-merge will still handle.

**Comment by Soaprman** [comment]
Well, I sure stumbled through that process, but it's all in now. Let me know if anything broke I guess!

**Pull request closed without merging**
