### PR TITLE
Inventory Editing

### PR DESCRIPTION
**Pull request by rilne**
Merging was a PitA, but looks good now.
Inventory lines are bundled up in their own panels, with a corresponding `ItemPanel` instance that manages updates within each panel (and event enabling/disabling, because circular events, bleh).
Combo box for item picking isn't working (yet), but will display correctly.
Enables/disables the forge/charges toggles based on item type (yes, I could combine them, it would be annoying).
Additionally, the raw hex string is displayed for each item, which is editable (so, you can change items there if you're feeling adventurous)

Your skill box handling code probably doesn't need 5 copies of each thing for each skill, could use a similar trick to my `ItemPanel` (closure abuse! yay!), but since I'm not messing with that right now I just left it.

Also, slight bugfix, I had screwed up the byte ordering for the hair colors. Should be good now.

### CODE REVIEW

**Comment by RainThunder** [comment]
I have to say, your repository history is a bit mess. You should follow [this](http://stackoverflow.com/questions/7244321/how-to-update-a-github-forked-repository) to update your repository properly. Inventory editing is a good feature btw.

**Comment by rilne** [comment]
Yeah, I finished a tricky merge, right in time for @Soaprman to have committed another set of conflicting changes, which I had to merge again.
Most of git's branch/history tools are kinda arcane to me, that said, source control is an inherently hard problem.

**Comment by Soaprman** [comment]
Aw maaaannnn, I was looking forward to working on this after skills. :p

You did it about the same way I would have done it, though. Probably soon I'll also update skills to be the same way because yeah, Form1 is getting hella cluttered. I just committed what I had because it was already a pretty large set of changes and it was in a working state.

If you guys are going to continue adding such large pieces of functionality, we might want to come up with some way to indicate who's working on what, even if it's something like opening an issue and assigning it to yourself. I can't say I expected to be receiving contributions this large when I started the project, and as a total amateur to git (I've used other source control stuff though like TFS), it's all a bit overwhelming. Of course, having to deal with conflicts is a reality regardless of which source control you use, and git will be just like anything else once I've put together a decent workflow.

I think my next changes are going to just be refactoring stuff and fixing bugs and then I'll do another release.

**Comment by Soaprman** [comment]
Alright, yeah, this merge wiped some of my skill stuff that I'm going to have to put back in.

Please don't add anything else until I've gotten things back in order.

**Comment by rilne** [comment]
If anything is missing, it should only be in the `Form1.designer.cs` file (so, controls gone, but code for their events/etc should have been merged correctly in `Form1.cs`).
...Which is terribad to merge, because it's generated, and it's used for storage of the design too? (who thought that was a good idea).
If the layout was at least stored as json or even xml, git could handle merging it better, but as it is, it's quite fragile.

As for why you got all these additions, easy: I am way too damn lazy to figure out the save format on my own, but once I have a nice base to work on, I can tear ahead adding stuff I want. So thanks for giving us a solid starting point.

And yeah, refactoring sounds like a good idea, heh.

**Comment by Soaprman** [comment]
I hear that once upon a time, partial classes weren't a thing and the generated designer code went into the same file as all the stuff the dev wrote. So I guess it could be worse!

I'm going to try splitting the GUI stuff into several "user controls" and see how that goes. That way most pieces of the GUI will be in separate files and merging will be way easier.

This is actually by far the biggest Forms application I've ever made, and the first one I've ever worked on where other developers were also involved. It's a learning experience, that's for sure.

**Comment by rilne** [comment]
`Item Panel` is basically already that, so yeah, just split it out and make it an actual control.
I haven't actually used the form designer before this, so bit of a learning curve for me too.
("I can't make arrays of controls, what? What the hell is with `MaskedTextBox`...oh. Several settings to make it non-stupid. Why can't C# just use `sprintf` like everyone else...and why are the format string specs on three different pages...")

**Comment by Soaprman** [comment]
@rilne The GUI refactor is done. You can carry on with more item stuff now. Let me know if I broke anything!

**Pull request merged**
